// Generated by github.com/davyxu/protoplus
// DO NOT EDIT!
package rpc

import (
	"github.com/davyxu/protoplus/proto"
	"github.com/davyxu/protoplus/wire"
	"unsafe"
	"reflect"
	"github.com/davyxu/cellnet"
	"github.com/davyxu/cellnet/codec"
)

var (
	_ *wire.Buffer
	_ = proto.Marshal
	_ unsafe.Pointer
	_ cellnet.MessageMeta
	_ codec.CodecRecycler
	_ reflect.Kind
)

type RemoteCallREQ struct {
	MsgID  uint32
	Data   []byte
	CallID int64
}

func (self *RemoteCallREQ) String() string { return proto.CompactTextString(self) }

func (self *RemoteCallREQ) Size() (ret int) {

	ret += wire.SizeUInt32(1, self.MsgID)

	ret += wire.SizeBytes(2, self.Data)

	ret += wire.SizeInt64(3, self.CallID)

	return
}

func (self *RemoteCallREQ) Marshal(buffer *wire.Buffer) error {

	wire.MarshalUInt32(buffer, 1, self.MsgID)

	wire.MarshalBytes(buffer, 2, self.Data)

	wire.MarshalInt64(buffer, 3, self.CallID)

	return nil
}

func (self *RemoteCallREQ) Unmarshal(buffer *wire.Buffer, fieldIndex uint64, wt wire.WireType) error {
	switch fieldIndex {
	case 1:
		v, err := wire.UnmarshalUInt32(buffer, wt)
		self.MsgID = v
		return err
	case 2:
		v, err := wire.UnmarshalBytes(buffer, wt)
		self.Data = v
		return err
	case 3:
		v, err := wire.UnmarshalInt64(buffer, wt)
		self.CallID = v
		return err

	}

	return wire.ErrUnknownField
}

type RemoteCallACK struct {
	MsgID  uint32
	Data   []byte
	CallID int64
}

func (self *RemoteCallACK) String() string { return proto.CompactTextString(self) }

func (self *RemoteCallACK) Size() (ret int) {

	ret += wire.SizeUInt32(1, self.MsgID)

	ret += wire.SizeBytes(2, self.Data)

	ret += wire.SizeInt64(3, self.CallID)

	return
}

func (self *RemoteCallACK) Marshal(buffer *wire.Buffer) error {

	wire.MarshalUInt32(buffer, 1, self.MsgID)

	wire.MarshalBytes(buffer, 2, self.Data)

	wire.MarshalInt64(buffer, 3, self.CallID)

	return nil
}

func (self *RemoteCallACK) Unmarshal(buffer *wire.Buffer, fieldIndex uint64, wt wire.WireType) error {
	switch fieldIndex {
	case 1:
		v, err := wire.UnmarshalUInt32(buffer, wt)
		self.MsgID = v
		return err
	case 2:
		v, err := wire.UnmarshalBytes(buffer, wt)
		self.Data = v
		return err
	case 3:
		v, err := wire.UnmarshalInt64(buffer, wt)
		self.CallID = v
		return err

	}

	return wire.ErrUnknownField
}

func init() {

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("protoplus"),
		Type:  reflect.TypeOf((*RemoteCallREQ)(nil)).Elem(),
		ID:    58645,
		New:   func() interface{} { return &RemoteCallREQ{} },
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("protoplus"),
		Type:  reflect.TypeOf((*RemoteCallACK)(nil)).Elem(),
		ID:    20476,
		New:   func() interface{} { return &RemoteCallACK{} },
	})

}
