// Code generated by protoc-gen-go.
// source: core.proto
// DO NOT EDIT!

/*
Package gamedef is a generated protocol buffer package.

It is generated from these files:
	core.proto

It has these top-level messages:
	SessionAccepted
	SessionConnected
	SessionClosed
	PeerInit
	PeerStart
	PeerStop
	RemoteCallREQ
	RemoteCallACK
	TestEchoACK
*/
package gamedef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 一个连接接入
type SessionAccepted struct {
}

func (m *SessionAccepted) Reset()                    { *m = SessionAccepted{} }
func (m *SessionAccepted) String() string            { return proto.CompactTextString(m) }
func (*SessionAccepted) ProtoMessage()               {}
func (*SessionAccepted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 已连接
type SessionConnected struct {
}

func (m *SessionConnected) Reset()                    { *m = SessionConnected{} }
func (m *SessionConnected) String() string            { return proto.CompactTextString(m) }
func (*SessionConnected) ProtoMessage()               {}
func (*SessionConnected) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 连接断开
type SessionClosed struct {
}

func (m *SessionClosed) Reset()                    { *m = SessionClosed{} }
func (m *SessionClosed) String() string            { return proto.CompactTextString(m) }
func (*SessionClosed) ProtoMessage()               {}
func (*SessionClosed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 端初始化
type PeerInit struct {
}

func (m *PeerInit) Reset()                    { *m = PeerInit{} }
func (m *PeerInit) String() string            { return proto.CompactTextString(m) }
func (*PeerInit) ProtoMessage()               {}
func (*PeerInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 端启动
type PeerStart struct {
}

func (m *PeerStart) Reset()                    { *m = PeerStart{} }
func (m *PeerStart) String() string            { return proto.CompactTextString(m) }
func (*PeerStart) ProtoMessage()               {}
func (*PeerStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 端停止
type PeerStop struct {
}

func (m *PeerStop) Reset()                    { *m = PeerStop{} }
func (m *PeerStop) String() string            { return proto.CompactTextString(m) }
func (*PeerStop) ProtoMessage()               {}
func (*PeerStop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// 请求
type RemoteCallREQ struct {
	MsgID  uint32 `protobuf:"varint,1,opt,name=MsgID,json=msgID" json:"MsgID,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	CallID int64  `protobuf:"varint,3,opt,name=CallID,json=callID" json:"CallID,omitempty"`
}

func (m *RemoteCallREQ) Reset()                    { *m = RemoteCallREQ{} }
func (m *RemoteCallREQ) String() string            { return proto.CompactTextString(m) }
func (*RemoteCallREQ) ProtoMessage()               {}
func (*RemoteCallREQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 回应
type RemoteCallACK struct {
	MsgID  uint32 `protobuf:"varint,1,opt,name=MsgID,json=msgID" json:"MsgID,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	CallID int64  `protobuf:"varint,3,opt,name=CallID,json=callID" json:"CallID,omitempty"`
}

func (m *RemoteCallACK) Reset()                    { *m = RemoteCallACK{} }
func (m *RemoteCallACK) String() string            { return proto.CompactTextString(m) }
func (*RemoteCallACK) ProtoMessage()               {}
func (*RemoteCallACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// ==========================================================
// 测试用消息
// ==========================================================
type TestEchoACK struct {
	Content string `protobuf:"bytes,1,opt,name=Content,json=content" json:"Content,omitempty"`
}

func (m *TestEchoACK) Reset()                    { *m = TestEchoACK{} }
func (m *TestEchoACK) String() string            { return proto.CompactTextString(m) }
func (*TestEchoACK) ProtoMessage()               {}
func (*TestEchoACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*SessionAccepted)(nil), "gamedef.SessionAccepted")
	proto.RegisterType((*SessionConnected)(nil), "gamedef.SessionConnected")
	proto.RegisterType((*SessionClosed)(nil), "gamedef.SessionClosed")
	proto.RegisterType((*PeerInit)(nil), "gamedef.PeerInit")
	proto.RegisterType((*PeerStart)(nil), "gamedef.PeerStart")
	proto.RegisterType((*PeerStop)(nil), "gamedef.PeerStop")
	proto.RegisterType((*RemoteCallREQ)(nil), "gamedef.RemoteCallREQ")
	proto.RegisterType((*RemoteCallACK)(nil), "gamedef.RemoteCallACK")
	proto.RegisterType((*TestEchoACK)(nil), "gamedef.TestEchoACK")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x40, 0x15, 0xda, 0x26, 0xf4, 0x4a, 0x54, 0xb0, 0x10, 0xca, 0x18, 0x79, 0x21, 0x13, 0x0b,
	0x5f, 0x50, 0x39, 0x1d, 0x22, 0x84, 0x44, 0x1d, 0x7e, 0xc0, 0xd8, 0x47, 0xa9, 0x94, 0xf8, 0x22,
	0xfb, 0xfe, 0x5f, 0xc8, 0x81, 0x0c, 0xec, 0x6c, 0xf7, 0xde, 0xe9, 0xde, 0x70, 0x00, 0x96, 0x02,
	0x3e, 0x4d, 0x81, 0x98, 0x44, 0x71, 0x36, 0x23, 0x3a, 0xfc, 0x94, 0x77, 0xb0, 0xef, 0x31, 0xc6,
	0x0b, 0xf9, 0x83, 0xb5, 0x38, 0x31, 0x3a, 0x29, 0xe0, 0xf6, 0x57, 0x29, 0xf2, 0x1e, 0x6d, 0x72,
	0x7b, 0x28, 0x17, 0x37, 0x50, 0x44, 0x27, 0x01, 0xae, 0xdf, 0x10, 0x43, 0xe7, 0x2f, 0x2c, 0x77,
	0xb0, 0x4d, 0x73, 0xcf, 0x26, 0xf0, 0xb2, 0xe8, 0x99, 0x26, 0x79, 0x82, 0x52, 0xe3, 0x48, 0x8c,
	0xca, 0x0c, 0x83, 0x3e, 0x9e, 0xc4, 0x3d, 0x6c, 0x5e, 0xe3, 0xb9, 0x6b, 0xab, 0xac, 0xce, 0x9a,
	0x52, 0x6f, 0xc6, 0x04, 0x42, 0xc0, 0xba, 0x35, 0x6c, 0xaa, 0xab, 0x3a, 0x6b, 0x6e, 0xf4, 0xda,
	0x19, 0x36, 0xe2, 0x01, 0xf2, 0x74, 0xd4, 0xb5, 0xd5, 0xaa, 0xce, 0x9a, 0x95, 0xce, 0xed, 0x4c,
	0x7f, 0x93, 0x07, 0xf5, 0xf2, 0x0f, 0xc9, 0x47, 0xd8, 0xbd, 0x63, 0xe4, 0xa3, 0xfd, 0xa2, 0x14,
	0xac, 0xa0, 0x50, 0xe4, 0x19, 0x3d, 0xcf, 0xc9, 0xad, 0x2e, 0xec, 0x0f, 0x7e, 0xe4, 0xf3, 0xef,
	0x9e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x97, 0x7f, 0xef, 0x2c, 0x49, 0x01, 0x00, 0x00,
}
