// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: coredef.proto
package coredef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("coredef.SessionAccepted", (*SessionAccepted)(nil), 3773660219)
	cellnet.RegisterMessageMeta("coredef.SessionConnected", (*SessionConnected)(nil), 1600911895)
	cellnet.RegisterMessageMeta("coredef.SessionClosed", (*SessionClosed)(nil), 511535871)
	cellnet.RegisterMessageMeta("coredef.PeerInit", (*PeerInit)(nil), 2753060681)
	cellnet.RegisterMessageMeta("coredef.PeerStart", (*PeerStart)(nil), 4251776880)
	cellnet.RegisterMessageMeta("coredef.PeerStop", (*PeerStop)(nil), 2891503523)
	cellnet.RegisterMessageMeta("coredef.UpstreamACK", (*UpstreamACK)(nil), 762952537)
	cellnet.RegisterMessageMeta("coredef.CloseClientACK", (*CloseClientACK)(nil), 379851567)
	cellnet.RegisterMessageMeta("coredef.DownstreamACK", (*DownstreamACK)(nil), 3820982158)
	cellnet.RegisterMessageMeta("coredef.RegisterRouterBackendACK", (*RegisterRouterBackendACK)(nil), 3006466942)
	cellnet.RegisterMessageMeta("coredef.RemoteCallREQ", (*RemoteCallREQ)(nil), 2289557267)
	cellnet.RegisterMessageMeta("coredef.RemoteCallACK", (*RemoteCallACK)(nil), 3811386225)
	cellnet.RegisterMessageMeta("coredef.TestEchoACK", (*TestEchoACK)(nil), 2828690649)
}
