// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: coredef.proto
package coredef

import (
	"github.com/davyxu/cellnet"
)

func init() {
	cellnet.RegisterMessageMeta("coredef.SessionAccepted", (*SessionAccepted)(nil), 3495179174)
	cellnet.RegisterMessageMeta("coredef.SessionConnected", (*SessionConnected)(nil), 3551021301)
	cellnet.RegisterMessageMeta("coredef.SessionClosed", (*SessionClosed)(nil), 3480086952)
	cellnet.RegisterMessageMeta("coredef.PeerInit", (*PeerInit)(nil), 1093282599)
	cellnet.RegisterMessageMeta("coredef.PeerStart", (*PeerStart)(nil), 4118877561)
	cellnet.RegisterMessageMeta("coredef.PeerStop", (*PeerStop)(nil), 1231725517)
	cellnet.RegisterMessageMeta("coredef.UpstreamACK", (*UpstreamACK)(nil), 2641300668)
	cellnet.RegisterMessageMeta("coredef.CloseClientACK", (*CloseClientACK)(nil), 1804957325)
	cellnet.RegisterMessageMeta("coredef.DownstreamACK", (*DownstreamACK)(nil), 2253519174)
	cellnet.RegisterMessageMeta("coredef.RegisterRouterBackendACK", (*RegisterRouterBackendACK)(nil), 4109904072)
	cellnet.RegisterMessageMeta("coredef.RemoteCallREQ", (*RemoteCallREQ)(nil), 3435750312)
	cellnet.RegisterMessageMeta("coredef.RemoteCallACK", (*RemoteCallACK)(nil), 2811469770)
	cellnet.RegisterMessageMeta("coredef.TestEchoACK", (*TestEchoACK)(nil), 970725711)
}
