// Code generated by protoc-gen-go.
// source: coredef.proto
// DO NOT EDIT!

/*
Package coredef is a generated protocol buffer package.

It is generated from these files:
	coredef.proto

It has these top-level messages:
	SessionAccepted
	SessionConnected
	SessionClosed
	PeerInit
	PeerStart
	PeerStop
	UpstreamACK
	CloseClientACK
	DownstreamACK
	RegisterRouterBackendACK
	RemoteCallREQ
	RemoteCallACK
	TestEchoACK
*/
package coredef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 一个连接接入
type SessionAccepted struct {
}

func (m *SessionAccepted) Reset()                    { *m = SessionAccepted{} }
func (m *SessionAccepted) String() string            { return proto.CompactTextString(m) }
func (*SessionAccepted) ProtoMessage()               {}
func (*SessionAccepted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 已连接
type SessionConnected struct {
}

func (m *SessionConnected) Reset()                    { *m = SessionConnected{} }
func (m *SessionConnected) String() string            { return proto.CompactTextString(m) }
func (*SessionConnected) ProtoMessage()               {}
func (*SessionConnected) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 连接断开
type SessionClosed struct {
}

func (m *SessionClosed) Reset()                    { *m = SessionClosed{} }
func (m *SessionClosed) String() string            { return proto.CompactTextString(m) }
func (*SessionClosed) ProtoMessage()               {}
func (*SessionClosed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 端初始化
type PeerInit struct {
}

func (m *PeerInit) Reset()                    { *m = PeerInit{} }
func (m *PeerInit) String() string            { return proto.CompactTextString(m) }
func (*PeerInit) ProtoMessage()               {}
func (*PeerInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 端启动
type PeerStart struct {
}

func (m *PeerStart) Reset()                    { *m = PeerStart{} }
func (m *PeerStart) String() string            { return proto.CompactTextString(m) }
func (*PeerStart) ProtoMessage()               {}
func (*PeerStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 端停止
type PeerStop struct {
}

func (m *PeerStop) Reset()                    { *m = PeerStop{} }
func (m *PeerStop) String() string            { return proto.CompactTextString(m) }
func (*PeerStop) ProtoMessage()               {}
func (*PeerStop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// 路由上行数据
// router -> backend
type UpstreamACK struct {
	MsgID    uint32 `protobuf:"varint,1,opt,name=MsgID,json=msgID" json:"MsgID,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	ClientID int64  `protobuf:"varint,3,opt,name=ClientID,json=clientID" json:"ClientID,omitempty"`
}

func (m *UpstreamACK) Reset()                    { *m = UpstreamACK{} }
func (m *UpstreamACK) String() string            { return proto.CompactTextString(m) }
func (*UpstreamACK) ProtoMessage()               {}
func (*UpstreamACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 关闭客户端
// backend -> router
type CloseClientACK struct {
	ClientID int64 `protobuf:"varint,1,opt,name=ClientID,json=clientID" json:"ClientID,omitempty"`
}

func (m *CloseClientACK) Reset()                    { *m = CloseClientACK{} }
func (m *CloseClientACK) String() string            { return proto.CompactTextString(m) }
func (*CloseClientACK) ProtoMessage()               {}
func (*CloseClientACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// 路由下行数据
// backend -> router
type DownstreamACK struct {
	MsgID    uint32  `protobuf:"varint,1,opt,name=MsgID,json=msgID" json:"MsgID,omitempty"`
	Data     []byte  `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	ClientID []int64 `protobuf:"varint,3,rep,name=ClientID,json=clientID" json:"ClientID,omitempty"`
}

func (m *DownstreamACK) Reset()                    { *m = DownstreamACK{} }
func (m *DownstreamACK) String() string            { return proto.CompactTextString(m) }
func (*DownstreamACK) ProtoMessage()               {}
func (*DownstreamACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// 后台服务器到网关注册自己的连接
// backend -> router
type RegisterRouterBackendACK struct {
	Name string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *RegisterRouterBackendACK) Reset()                    { *m = RegisterRouterBackendACK{} }
func (m *RegisterRouterBackendACK) String() string            { return proto.CompactTextString(m) }
func (*RegisterRouterBackendACK) ProtoMessage()               {}
func (*RegisterRouterBackendACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// 请求
type RemoteCallREQ struct {
	MsgID  uint32 `protobuf:"varint,1,opt,name=MsgID,json=msgID" json:"MsgID,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	CallID int64  `protobuf:"varint,3,opt,name=CallID,json=callID" json:"CallID,omitempty"`
}

func (m *RemoteCallREQ) Reset()                    { *m = RemoteCallREQ{} }
func (m *RemoteCallREQ) String() string            { return proto.CompactTextString(m) }
func (*RemoteCallREQ) ProtoMessage()               {}
func (*RemoteCallREQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// 回应
type RemoteCallACK struct {
	MsgID  uint32 `protobuf:"varint,1,opt,name=MsgID,json=msgID" json:"MsgID,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	CallID int64  `protobuf:"varint,3,opt,name=CallID,json=callID" json:"CallID,omitempty"`
}

func (m *RemoteCallACK) Reset()                    { *m = RemoteCallACK{} }
func (m *RemoteCallACK) String() string            { return proto.CompactTextString(m) }
func (*RemoteCallACK) ProtoMessage()               {}
func (*RemoteCallACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

// ==========================================================
// 测试用消息
// ==========================================================
type TestEchoACK struct {
	Content string `protobuf:"bytes,1,opt,name=Content,json=content" json:"Content,omitempty"`
}

func (m *TestEchoACK) Reset()                    { *m = TestEchoACK{} }
func (m *TestEchoACK) String() string            { return proto.CompactTextString(m) }
func (*TestEchoACK) ProtoMessage()               {}
func (*TestEchoACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*SessionAccepted)(nil), "coredef.SessionAccepted")
	proto.RegisterType((*SessionConnected)(nil), "coredef.SessionConnected")
	proto.RegisterType((*SessionClosed)(nil), "coredef.SessionClosed")
	proto.RegisterType((*PeerInit)(nil), "coredef.PeerInit")
	proto.RegisterType((*PeerStart)(nil), "coredef.PeerStart")
	proto.RegisterType((*PeerStop)(nil), "coredef.PeerStop")
	proto.RegisterType((*UpstreamACK)(nil), "coredef.UpstreamACK")
	proto.RegisterType((*CloseClientACK)(nil), "coredef.CloseClientACK")
	proto.RegisterType((*DownstreamACK)(nil), "coredef.DownstreamACK")
	proto.RegisterType((*RegisterRouterBackendACK)(nil), "coredef.RegisterRouterBackendACK")
	proto.RegisterType((*RemoteCallREQ)(nil), "coredef.RemoteCallREQ")
	proto.RegisterType((*RemoteCallACK)(nil), "coredef.RemoteCallACK")
	proto.RegisterType((*TestEchoACK)(nil), "coredef.TestEchoACK")
}

func init() { proto.RegisterFile("coredef.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x52, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x54, 0xe9, 0x7b, 0x4b, 0x28, 0x58, 0x08, 0x45, 0x9c, 0x90, 0x2f, 0x70, 0x40, 0xbd, 0xf0,
	0x05, 0x25, 0xe9, 0xa1, 0x42, 0x20, 0xea, 0xd0, 0x0f, 0x30, 0xce, 0x52, 0x22, 0x12, 0x3b, 0xb2,
	0x17, 0xf1, 0xfb, 0xd8, 0x21, 0x45, 0x14, 0x89, 0x43, 0xc5, 0xc5, 0xda, 0x19, 0x8f, 0x67, 0x77,
	0xad, 0x81, 0x48, 0x19, 0x8b, 0x39, 0xbe, 0xcc, 0x6a, 0x6b, 0xc8, 0xb0, 0x61, 0x0b, 0xf9, 0x09,
	0x4c, 0x33, 0x74, 0xae, 0x30, 0x7a, 0xae, 0x14, 0xd6, 0x84, 0x39, 0x67, 0x70, 0xdc, 0x52, 0x89,
	0xd1, 0x1a, 0x55, 0xe0, 0xa6, 0x10, 0x6d, 0xb9, 0xd2, 0x38, 0x4f, 0x00, 0x8c, 0x1e, 0x11, 0xed,
	0x52, 0x17, 0xc4, 0x27, 0x30, 0x0e, 0x75, 0x46, 0xd2, 0xd2, 0xf6, 0x22, 0x23, 0x53, 0xf3, 0x0c,
	0x26, 0xeb, 0xda, 0x91, 0x45, 0x59, 0xcd, 0x93, 0x3b, 0x76, 0x0a, 0xfd, 0x7b, 0xb7, 0x59, 0xa6,
	0x71, 0xe7, 0xa2, 0x73, 0x15, 0x89, 0x7e, 0x15, 0x00, 0x63, 0xd0, 0x4b, 0x25, 0xc9, 0xf8, 0xc0,
	0x93, 0x87, 0xa2, 0x97, 0xfb, 0x9a, 0x9d, 0xc3, 0x28, 0x29, 0x0b, 0xd4, 0xe4, 0xc5, 0x5d, 0xcf,
	0x77, 0xc5, 0x48, 0xb5, 0x98, 0x5f, 0xc3, 0x51, 0x33, 0xc3, 0x97, 0x20, 0xf8, 0xfe, 0x54, 0x77,
	0x7e, 0xa9, 0xd7, 0x10, 0xa5, 0xe6, 0x43, 0xff, 0x7f, 0x88, 0xee, 0x8e, 0xed, 0x0c, 0x62, 0x81,
	0x9b, 0xc2, 0x11, 0x5a, 0x61, 0xde, 0xfd, 0x79, 0x2b, 0xd5, 0x1b, 0xea, 0x3c, 0x74, 0xf0, 0x5e,
	0x0f, 0xb2, 0xc2, 0xa6, 0xc1, 0x58, 0xf4, 0xb4, 0xaf, 0xf9, 0x0a, 0x22, 0x81, 0x95, 0x21, 0x4c,
	0x64, 0x59, 0x8a, 0xc5, 0x6a, 0x8f, 0x31, 0xce, 0x60, 0x10, 0x1e, 0x7d, 0xff, 0xc4, 0x40, 0x35,
	0x68, 0xd7, 0x72, 0xbf, 0xcd, 0xfe, 0xb2, 0xbc, 0x84, 0xc9, 0x13, 0x3a, 0x5a, 0xa8, 0x57, 0x13,
	0x0c, 0x63, 0x18, 0xfa, 0x04, 0x90, 0xdf, 0xb8, 0xdd, 0xc5, 0xa7, 0xa6, 0x81, 0xcf, 0x83, 0x26,
	0x45, 0x37, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x74, 0x7c, 0x10, 0xbc, 0x56, 0x02, 0x00, 0x00,
}
