// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package gamedef

import (
	"reflect"
	"github.com/davyxu/cellnet/codec/sproto"
)

type TestEchoACK struct {
	Content string `sproto:"string,0,name=Content"`
}

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*TestEchoACK)(nil)).Elem(),
}

func init() {
	sprotocodec.AutoRegisterMessageMeta(SProtoStructs)
}
