// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!
// Source: core.sproto

package gamedef

import (
	"reflect"
)

// core.sproto

type SessionAccepted struct {
}

type SessionConnected struct {
}

type SessionAcceptFailed struct {
	Reason string `sproto:"string,0,name=Reason"`
}

type SessionConnectFailed struct {
	Reason string `sproto:"string,0,name=Reason"`
}

type SessionClosed struct {
}

type TestEchoACK struct {
	Content string `sproto:"string,0,name=Content"`
}

var SProtoStructs = []reflect.Type{
	// core.sproto
	reflect.TypeOf((*SessionAccepted)(nil)).Elem(),
	reflect.TypeOf((*SessionConnected)(nil)).Elem(),
	reflect.TypeOf((*SessionAcceptFailed)(nil)).Elem(),
	reflect.TypeOf((*SessionConnectFailed)(nil)).Elem(),
	reflect.TypeOf((*SessionClosed)(nil)).Elem(),
	reflect.TypeOf((*TestEchoACK)(nil)).Elem(),
}
