// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package gamedef

import (
	"reflect"

	"github.com/davyxu/cellnet/codec/sproto"
	"github.com/davyxu/goobjfmt"
)

type TestEchoACK struct {
	Content string `sproto:"string,0,name=Content"`
}

func (self *TestEchoACK) String() string { return goobjfmt.CompactTextString(self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*TestEchoACK)(nil)).Elem(), // 1899977859
}

func init() {
	sprotocodec.AutoRegisterMessageMeta(SProtoStructs)
}
