// Generated by github.com/davyxu/cellnet/objprotogen
// DO NOT EDIT!
package coredef

import (
	"github.com/davyxu/cellnet"
	"github.com/davyxu/goobjfmt"
	"reflect"
)

func (self *SessionAccepted) String() string      { return goobjfmt.CompactTextString(self) }
func (self *SessionConnected) String() string     { return goobjfmt.CompactTextString(self) }
func (self *SessionAcceptFailed) String() string  { return goobjfmt.CompactTextString(self) }
func (self *SessionConnectFailed) String() string { return goobjfmt.CompactTextString(self) }
func (self *SessionClosed) String() string        { return goobjfmt.CompactTextString(self) }
func (self *RemoteCallACK) String() string        { return goobjfmt.CompactTextString(self) }

func init() {

	cellnet.RegisterMessageMeta("binary", "coredef.SessionAccepted", reflect.TypeOf((*SessionAccepted)(nil)).Elem(), 2087448307)
	cellnet.RegisterMessageMeta("binary", "coredef.SessionConnected", reflect.TypeOf((*SessionConnected)(nil)).Elem(), 3159799620)
	cellnet.RegisterMessageMeta("binary", "coredef.SessionAcceptFailed", reflect.TypeOf((*SessionAcceptFailed)(nil)).Elem(), 3257237101)
	cellnet.RegisterMessageMeta("binary", "coredef.SessionConnectFailed", reflect.TypeOf((*SessionConnectFailed)(nil)).Elem(), 290677256)
	cellnet.RegisterMessageMeta("binary", "coredef.SessionClosed", reflect.TypeOf((*SessionClosed)(nil)).Elem(), 1747213404)
	cellnet.RegisterMessageMeta("binary", "coredef.RemoteCallACK", reflect.TypeOf((*RemoteCallACK)(nil)).Elem(), 14297662)
}
