package main

import (
	"github.com/davyxu/pbmeta"
)

func printFile(gen *Generator, file *pbmeta.FileDescriptor) {

	gen.Println("// This code is generated by github.com/davyxu/cellnet/protoc-gen-msg, DO NOT EDIT")
	gen.Println("// Generated from: ", file.FileName())

	for _, v := range file.Define.Dependency {
		gen.Println("// Note: requires additional type generated from: ", v)
	}

	gen.Println("package ", file.PackageName())
	gen.Println()
	gen.Println("import (")
	gen.In()
	gen.Println("\"github.com/davyxu/cellnet\"")
	gen.Out()
	gen.Println(")")

	gen.Println()
	gen.Println("func init() {")
	gen.In()

	for i := 0; i < file.MessageCount(); i++ {

		msg := file.Message(i)

		gen.Println("cellnet.RegisterMessage(\"", file.PackageName(), ".", msg.Name(), "\", (*", msg.Name(), ")(nil))")
	}

	gen.Out()
	gen.Println("}")

}
