// Code generated by protoc-gen-go.
// source: gamedef.proto
// DO NOT EDIT!

/*
Package gamedef is a generated protocol buffer package.

It is generated from these files:
	gamedef.proto

It has these top-level messages:
	TestEchoACK
*/
package gamedef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ==========================================================
// 测试用消息
// ==========================================================
type TestEchoACK struct {
	Content string `protobuf:"bytes,1,opt,name=Content,json=content" json:"Content,omitempty"`
}

func (m *TestEchoACK) Reset()                    { *m = TestEchoACK{} }
func (m *TestEchoACK) String() string            { return proto.CompactTextString(m) }
func (*TestEchoACK) ProtoMessage()               {}
func (*TestEchoACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*TestEchoACK)(nil), "gamedef.TestEchoACK")
}

func init() { proto.RegisterFile("gamedef.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0xcc, 0x4d,
	0x4d, 0x49, 0x4d, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xd4, 0xb9,
	0xb8, 0x43, 0x52, 0x8b, 0x4b, 0x5c, 0x93, 0x33, 0xf2, 0x1d, 0x9d, 0xbd, 0x85, 0x24, 0xb8, 0xd8,
	0x9d, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xd8, 0x93,
	0x21, 0xdc, 0x24, 0x36, 0xb0, 0x46, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xc1, 0x9b,
	0xa0, 0x49, 0x00, 0x00, 0x00,
}
