// Generated by github.com/davyxu/protoplus
// DO NOT EDIT!
package relay

import (
	"github.com/davyxu/protoplus/proto"
	"unsafe"
	"reflect"
	"github.com/davyxu/cellnet"
	"github.com/davyxu/cellnet/codec"
)

var (
	_ *proto.Buffer
	_ unsafe.Pointer
	_ cellnet.MessageMeta
	_ codec.CodecRecycler
	_ reflect.Kind
)

type RelayACK struct {
	Msg        []byte  // 数据消息转换后传输bytes
	MsgID      uint32  // 消息ID
	Bytes      []byte  // 数据bytes
	Int64      int64   // 透传int64
	Int64Slice []int64 // 透传int64切片
	Str        string
}

func (self *RelayACK) String() string { return proto.CompactTextString(self) }

func (self *RelayACK) Size() (ret int) {

	ret += proto.SizeBytes(1, self.Msg)

	ret += proto.SizeUInt32(2, self.MsgID)

	ret += proto.SizeBytes(3, self.Bytes)

	ret += proto.SizeInt64(4, self.Int64)

	ret += proto.SizeInt64Slice(5, self.Int64Slice)

	ret += proto.SizeString(6, self.Str)

	return
}

func (self *RelayACK) Marshal(buffer *proto.Buffer) error {

	proto.MarshalBytes(buffer, 1, self.Msg)

	proto.MarshalUInt32(buffer, 2, self.MsgID)

	proto.MarshalBytes(buffer, 3, self.Bytes)

	proto.MarshalInt64(buffer, 4, self.Int64)

	proto.MarshalInt64Slice(buffer, 5, self.Int64Slice)

	proto.MarshalString(buffer, 6, self.Str)

	return nil
}

func (self *RelayACK) Unmarshal(buffer *proto.Buffer, fieldIndex uint64, wt proto.WireType) error {
	switch fieldIndex {
	case 1:
		v, err := proto.UnmarshalBytes(buffer, wt)
		self.Msg = v
		return err
	case 2:
		v, err := proto.UnmarshalUInt32(buffer, wt)
		self.MsgID = v
		return err
	case 3:
		v, err := proto.UnmarshalBytes(buffer, wt)
		self.Bytes = v
		return err
	case 4:
		v, err := proto.UnmarshalInt64(buffer, wt)
		self.Int64 = v
		return err
	case 5:
		v, err := proto.UnmarshalInt64Slice(buffer, wt)
		self.Int64Slice = append(self.Int64Slice, v...)
		return err
	case 6:
		v, err := proto.UnmarshalString(buffer, wt)
		self.Str = v
		return err

	}

	return proto.ErrUnknownField
}

func init() {

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("protoplus"),
		Type:  reflect.TypeOf((*RelayACK)(nil)).Elem(),
		ID:    45545,
	})

}
