// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package chatproto is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	ChatREQ
	ChatACK
*/
package chatproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatREQ struct {
	Content string `protobuf:"bytes,1,opt,name=Content,json=content" json:"Content,omitempty"`
}

func (m *ChatREQ) Reset()                    { *m = ChatREQ{} }
func (m *ChatREQ) String() string            { return proto.CompactTextString(m) }
func (*ChatREQ) ProtoMessage()               {}
func (*ChatREQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatREQ) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ChatACK struct {
	Content string `protobuf:"bytes,1,opt,name=Content,json=content" json:"Content,omitempty"`
	Id      int64  `protobuf:"varint,2,opt,name=Id,json=id" json:"Id,omitempty"`
}

func (m *ChatACK) Reset()                    { *m = ChatACK{} }
func (m *ChatACK) String() string            { return proto.CompactTextString(m) }
func (*ChatACK) ProtoMessage()               {}
func (*ChatACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatACK) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ChatACK) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ChatREQ)(nil), "chatproto.ChatREQ")
	proto.RegisterType((*ChatACK)(nil), "chatproto.ChatACK")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x25, 0x65, 0x2e, 0x76,
	0xe7, 0x8c, 0xc4, 0x92, 0x20, 0xd7, 0x40, 0x21, 0x09, 0x2e, 0x76, 0xe7, 0xfc, 0xbc, 0x92, 0xd4,
	0xbc, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xf6, 0x64, 0x08, 0x57, 0xc9, 0x18, 0xa2,
	0xc8, 0xd1, 0xd9, 0x1b, 0xb7, 0x22, 0x21, 0x3e, 0x2e, 0x26, 0xcf, 0x14, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xe6, 0x20, 0xa6, 0xcc, 0x94, 0x24, 0x36, 0xb0, 0x05, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc0, 0x5a, 0xfe, 0x6e, 0x79, 0x00, 0x00, 0x00,
}
